# This is a basic workflow to help you get started with Actions

name: aks-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [release/*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: knpro.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker Build
        run: |
          docker build --build-arg HUGO_BASEURL=http://kirk.newson.nz -t knpro.azurecr.io/kn-website:${{ github.sha }} .
          docker push knpro.azurecr.io/kn-website:${{ github.sha }}
      - name: AKS Context
        uses: Azure/aks-set-context@v1
        with:
          creds: ''
          resource-group: 'AKS-KN-Professional'
          cluster-name: 'kn'
        id: login
      - name: Image Pull Secret
        uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: contoso.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: knpro-image-pull-secret
      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: resume
          manifests: |
            deploy/deployment.yml
            deploy/service.yml
          images: 'knpro.azurecr.io/kn-website:${{ github.sha }}'
          imagepullsecrets: |
            knpro-image-pull-secret
